version: '3'
services:
  test:
    build: .
    volumes:
      - ./reports:/app/reports
      - ./src/fixtures:/app/src/fixtures
    environment:
      - CI=true
      - NODE_ENV=ci
      - PWDEBUG=0
      - RETRIES=2
    user: root
    
    # Runs the updated 'docker:test' which uses 'test:all' script 
    # (assuming no explicit 'command' override is present in your docker-compose file)
    command: npm run docker:test 
    restart: "no"
