version: '3'
services:
  test:
    build: .
    volumes:
      # CRITICAL PLUMBING: Maps the container results to the host machine
      - ./reports:/app/reports
      - ./src/fixtures:/app/src/fixtures
    environment:
      - CI=true
      - NODE_ENV=ci
      - PWDEBUG=0
      - RETRIES=2
    user: root
    
    # Ensures the service runs the updated Allure script
    command: npm run test:all
    restart: "no" # Necessary for --exit-code-from test to work
