name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# CRITICAL: Sets permissions required for Actions
permissions:
  contents: read
  pages: write 
  id-token: write 

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # 1. NPM CACHE
    - name: Cache Node Modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # 2. DOWNLOAD HISTORY (For Trends - ROBUST VERSION)
    - name: Download Allure history
      if: always()
      run: |
        PREVIOUS_HISTORY_DIR=reports/allure-results/history
        REPORT_BASE_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
        
        mkdir -p ${PREVIOUS_HISTORY_DIR}

        # Check if history.json exists on the live site before attempting download
        if curl -s -f -o /dev/null ${REPORT_BASE_URL}/history/history.json; then
          echo "Previous history found, downloading all files in the history directory..."
          
          # CRITICAL FIX: Use robust wget command to download *all* necessary files for trend charts.
          wget -r -l1 -np -nd -A '*' ${REPORT_BASE_URL}/history/ -P ${PREVIOUS_HISTORY_DIR} || true
        else
          echo "No previous history found. Generating first report with no trend data."
        fi

    - name: Set up Docker Compose
      uses: ndeloof/install-compose-action@v0.0.1
    
    # 3. BUILD AND RUN TESTS
    - name: Build and run tests in Docker
      run: |
        docker-compose up --build --exit-code-from test
    
    # 4. FIX Permissions
    - name: Fix permissions for Allure results
      if: always()
      run: |
        sudo chmod -R 777 reports/allure-results

    # 4.5. CRITICAL FIX: Convert Cucumber JSON to Allure Results on the host machine (STABLE & FAST)
    - name: Convert Cucumber JSON to Allure Format (Stable)
      if: always()
      run: |
        # CRITICAL FIX: Run 'npm ci' to install dependencies necessary for 'generate-allure.js'
        # This will be fast due to the cache from Step 1.
        npm ci 
        
        if [ -f reports/cucumber.json ]; then
          node tests/support/generate-allure.js
          echo "Conversion successful."
        else
          echo "Warning: reports/cucumber.json not found. Allure report may be empty."
        fi

    # 5. INSTALL ALLURE & GENERATE REPORT
    - name: Generate Allure Report
      if: always()
      run: |
        # Install Allure CLI (needed on host machine)
        curl -o allure-2.24.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
        sudo tar -zxvf allure-2.24.1.tgz -C /opt/
        sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
        sudo mkdir -p reports/allure-results reports/allure-report
        sudo chmod -R 777 reports
        sudo chown -R $USER:$USER reports
        
        # Generate the HTML report using the downloaded history for trends
        allure generate reports/allure-results --clean -o reports/allure-report

        # Start of History Persistence & Deployment Prep (CRITICAL for Trend)
        
        # 1. Copy the NEW history from the generated report folder back to the results folder (for next run's DOWNLOAD step)
        NEW_HISTORY_SOURCE=reports/allure-report/history
        NEW_HISTORY_DEST=reports/allure-results/history
        mkdir -p ${NEW_HISTORY_DEST}
        cp -r ${NEW_HISTORY_SOURCE}/. ${NEW_HISTORY_DEST} || true
        
        # 2. Prepare the final deployment folder
        mkdir -p reports/allure-report-with-header
        
        # Install rsync for robust copying (needed for the next step)
        sudo apt-get update && sudo apt-get install -y rsync || true
        
        # CRITICAL FIX: Use rsync for robust and complete file copying, ensuring the history folder is included
        rsync -a reports/allure-report/ reports/allure-report-with-header/
        
        # Download favicon
        curl -s https://raw.githubusercontent.com/microsoft/playwright/main/assets/playwright-logo.svg > reports/allure-report-with-header/favicon.svg
        
        # CACHE BUSTING: Inject no-cache meta tags into index.html
        CACHE_BUSTING_TAGS='<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate"><meta http-equiv="Pragma" content="no-cache"><meta http-equiv="Expires" content="0">'
        
        # Update the report HTML with our custom content, favicon, and cache tags
        sed -i "s|<head>|<head>$CACHE_BUSTING_TAGS<link rel=\"icon\" type=\"image/svg+xml\" href=\"favicon.svg\"><title>Playwright E2E Test Report</title>|" reports/allure-report-with-header/index.html
        
        # CRITICAL FIX: Strip all newlines (tr -d '\n') from the header and metadata before processing.
        HEADER_CONTENT=$(cat header.html | tr -d '\n')
        METADATA_CONTENT=$(cat metadata.html | tr -d '\n')
        CUSTOM_HEADER_CONTENT="$HEADER_CONTENT$METADATA_CONTENT"
        
        # Robustly insert custom header/metadata after the <body> tag
        ESCAPED_CONTENT=$(echo "$CUSTOM_HEADER_CONTENT" | sed 's/[\&/]/\\&/g')
        
        sed -i "/<body>/a\\
        $ESCAPED_CONTENT" reports/allure-report-with-header/index.html


    # 6. DEPLOY TO GITHUB PAGES
    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v4

    - name: Upload Report to Pages
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: reports/allure-report-with-header 
        retention-days: 90

    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4

    # 7. DELETE DOCKER CACHE (If successful)
    - name: Delete Docker Build Cache
      if: success()
      run: docker builder prune -f
