name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and run tests in Docker
      run: |
        docker-compose up --build --exit-code-from test
    
    - name: Generate Allure Report
      if: always()
      run: npm run report:generate
    
    - name: Setup Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v3

    - name: Upload artifact
      if: success() && github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v2
      with:
        path: reports/allure-report

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v2

  test-direct:
    runs-on: ubuntu-latest
    needs: test-docker
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run tests
      run: npm run test:all
    
    - name: Generate Allure Report
      if: always()
      run: |
        npm run report:generate
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/
        retention-days: 30