name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    # Download history from GitHub Pages
    - name: Download Allure history
      if: always()
      run: |
        PREVIOUS_HISTORY_DIR=allure-history
        # Create history directory
        mkdir -p reports/allure-results/history
        # Download history if it exists
        if curl -s -o /dev/null -w "%{http_code}" https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/ | grep -q "200"; then
          wget https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/history.json -P reports/allure-results/history/ || true
          wget https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/history-trend.json -P reports/allure-results/history/ || true
          wget https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/duration-trend.json -P reports/allure-results/history/ || true
          wget https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/categories-trend.json -P reports/allure-results/history/ || true
          wget https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/retry-trend.json -P reports/allure-results/history/ || true
        fi

    - name: Set up Docker Compose
      uses: ndeloof/install-compose-action@v0.0.1
    
    - name: Build and run tests in Docker
      run: |
        docker-compose up --build --exit-code-from test
    
    - name: Install Allure and setup reports directory
      if: always()
      run: |
        curl -o allure-2.24.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
        sudo tar -zxvf allure-2.24.1.tgz -C /opt/
        sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
        sudo mkdir -p reports/allure-results reports/allure-report
        sudo chmod -R 777 reports
        sudo chown -R $USER:$USER reports
    
    - name: Generate Allure Report
      if: always()
      run: npm run report:generate

    - name: Update Report Index and Preserve History
      if: success() && github.ref == 'refs/heads/main'
      run: |
        # Add custom index page header
        echo '<h1>Playwright E2E BDD Framework - Test Reports</h1>' > header.html
        # Combine with Allure report
        mkdir -p reports/allure-report-with-header
        cp -r reports/allure-report/* reports/allure-report-with-header/
        # Create history directory in published report
        mkdir -p reports/allure-report-with-header/history
        # Copy history files to published report
        cp -r reports/allure-results/history/* reports/allure-report-with-header/history/ || true
        # Update index page with header
        cat header.html | cat - reports/allure-report-with-header/index.html > temp && mv temp reports/allure-report-with-header/index.html

    - name: Setup Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4

    - name: Upload Report to Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: reports/allure-report-with-header
        retention-days: 30

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4

  test-direct:
    runs-on: ubuntu-latest
    needs: test-docker
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run tests
      run: npm run test:all
    
    - name: Install Allure and setup reports directory
      if: always()
      run: |
        curl -o allure-2.24.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
        sudo tar -zxvf allure-2.24.1.tgz -C /opt/
        sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
        sudo mkdir -p reports/allure-results reports/allure-report
        sudo chmod -R 777 reports
        sudo chown -R $USER:$USER reports
    
    - name: Generate Allure Report
      if: always()
      run: |
        npm run report:generate
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/
        retention-days: 30